### ISSUE TITLE
I found two error!

### ISSUE THREAD

**Issue by blackcodersec** [defparam/lemma#1]
When I run `./build.sh`, I found this type of error.

![image](https://github.com/user-attachments/assets/879d6220-37ce-483a-882a-3d0c957f7aa8)

![image](https://github.com/user-attachments/assets/d39a907c-fd95-41f3-bb9a-3755164b3563)

![image](https://github.com/user-attachments/assets/ac6f4bab-59ce-4738-bc8c-037b73074f27)

**Comment by defparam** [comment]
Sorry! temporary bug. Should be fixed now
