### ISSUE TITLE
Lemma cli always returns 404

### ISSUE THREAD

**Issue by fyoorer** [defparam/lemma#2]
Lemma works fine from the webui but CLI always returns 404

![Screenshot 2024-07-17 at 12 23 51 PM](https://github.com/user-attachments/assets/34efb992-bf6f-4486-9154-7da4cc441bcc)

I have already configured lemma URL in `lemma.ini` file with key

**Comment by defparam** [comment]
Try to reset your lambda URL by doing `lemma -l`
If that doesn't work could you try installing lemmacli in a python venv and retrying the test?

**Comment by fyoorer** [comment]
installing in a venv worked
